<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1509051995461" stop="1509052012130" version="1.5.4" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default Suite : sandbox</name>
    <title>Default Suite : sandbox</title>
    <test-cases>
        <test-case start="1509051995580" stop="1509051999693" status="passed">
            <name>testBadGroupCreation</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="sandbox"/>
                <label name="testClass" value="pft.module.addressbook.tests.GroupCreationTests"/>
                <label name="testMethod" value="testBadGroupCreation"/>
                <label name="host" value="MUKHAN2-L2"/>
                <label name="thread" value="14072@MUKHAN2-L2.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1509051999743" stop="1509052006116" status="failed">
            <name>testGroupCreation[GroupData{id='2147483647', name='test 0'}]</name>
            <failure>
                <message>AssertionError: 
Expected: &lt;[GroupData{id='1', name='test 0'}]&gt;
     but: was &lt;[GroupData{id='1', name='test 0'}]&gt;</message>
                <stack-trace>java.lang.AssertionError: 
Expected: &lt;[GroupData{id='1', name='test 0'}]&gt;
     but: was &lt;[GroupData{id='1', name='test 0'}]&gt;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at pft.module.addressbook.tests.GroupCreationTests.testGroupCreation(GroupCreationTests.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="sandbox"/>
                <label name="testClass" value="pft.module.addressbook.tests.GroupCreationTests"/>
                <label name="testMethod" value="testGroupCreation"/>
                <label name="host" value="MUKHAN2-L2"/>
                <label name="thread" value="14072@MUKHAN2-L2.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1509052006126" stop="1509052012120" status="failed">
            <name>testGroupCreation[GroupData{id='2147483647', name='test 1'}]</name>
            <failure>
                <message>AssertionError: 
Expected: &lt;[GroupData{id='2', name='test 1'}, GroupData{id='1', name='test 0'}]&gt;
     but: was &lt;[GroupData{id='1', name='test 0'}, GroupData{id='2', name='test 1'}]&gt;</message>
                <stack-trace>java.lang.AssertionError: 
Expected: &lt;[GroupData{id='2', name='test 1'}, GroupData{id='1', name='test 0'}]&gt;
     but: was &lt;[GroupData{id='1', name='test 0'}, GroupData{id='2', name='test 1'}]&gt;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at pft.module.addressbook.tests.GroupCreationTests.testGroupCreation(GroupCreationTests.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="sandbox"/>
                <label name="testClass" value="pft.module.addressbook.tests.GroupCreationTests"/>
                <label name="testMethod" value="testGroupCreation"/>
                <label name="host" value="MUKHAN2-L2"/>
                <label name="thread" value="14072@MUKHAN2-L2.main(1)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
